name: Docker image buildx and push
on: [push]
jobs:
  Docker-Build-Push:
    runs-on: ubuntu-latest
    steps:
      -
        name: check out repository code
        uses: actions/checkout@v2
      -
        name: list docker image
        run: docker image ls
